name = "nuxt-ichibanboshi"
account_id = "24b45709d060d957340180e995f0d373"
main = "./.output/server/index.mjs"
compatibility_date = "2025-07-15"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".output/public"

[vars]
NUXT_SALES_API_BASE = "https://rust-ichiban.mtamaramu.com"
NUXT_PUBLIC_ALC_API_BASE = "https://alc-api.ippoan.org"
NUXT_CF_ACCESS_CLIENT_ID = "44252f056e72590bee3c4bb8f85de841.access"
# NUXT_CF_ACCESS_CLIENT_SECRET は wrangler secret で設定

[env.staging]
name = "nuxt-ichibanboshi-staging"

[[env.staging.routes]]
pattern = "ichibanboshi-staging.ippoan.org"
custom_domain = true
[env.staging.vars]
NUXT_SALES_API_BASE = "https://rust-ichiban.mtamaramu.com"
NUXT_PUBLIC_ALC_API_BASE = "https://rust-alc-api-staging-566bls5vfq-an.a.run.app"
NUXT_CF_ACCESS_CLIENT_ID = "44252f056e72590bee3c4bb8f85de841.access"
NUXT_PUBLIC_AUTH_WORKER_URL = "https://auth-staging.ippoan.org"
